nelmio_cors:
    defaults:
        allow_credentials : true 
        origin_regex : true 
        # allow_origin: ['%env(CORS_ALLOW_ORIGIN)%'] 
        allow_origin : ['https://FRONT-URL.com'] 
        allow_methods : ['GET', 'OPTIONS', ' POST', 'PUT', 'PATCH', 'DELETE'] 
        allow_headers : ['Content-Type', 'Authorization'] 
        max_age : 3600 
    paths :
         ' ^/ ' : ~